language: node_js
node_js:
  - 10
git:
  depth: 1
branches:
  except:
  - /^dev-.*$/

# Build life-cycle
install:
  - npm install
before_script:
  - "cp app/database/db.sample.json app/database/db.json"
script: npm run test  