language: node_js
node_js:
  - 10
git:
  depth: 1
branches:
  except:
  - /^dev-.*$/

# Build life-cycle
install:
  - npm install
before_script:
  - "cp app/database/db.sample.json app/database/db.json"
script:
  - make test
  - make image
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make deploy;
    fi