#!/bin/bash
TAG_SHORT=$(git describe --tags --abbrev=0)
IMAGE_NAME=open-zhy/freshbooks-mock
docker build -t $(IMAGE_NAME) -f Dockerfile .
docker tag $(IMAGE_NAME) $(IMAGE_NAME):$(TAG_SHORT)
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push $(IMAGE_NAME):$(TAG_SHORT)